### ISSUE TITLE
Questions regarding quantile threshold

### ISSUE THREAD

**Issue by danielvu-31** [boschresearch/Divide-and-Bind#3]
Thank you for your amazing paper. I have a small question. 
[https://github.com/boschresearch/Divide-and-Bind/blob/main/divide_and_bind/pipeline_divide_and_bind.py#L811](url)

Should it be `thresh_color = quantile * color_image_.max()` instead of `thresh_color = quantile * image_.max()`? Thank you.

**Comment by YumengLi007** [comment]
Hi @danielvu-31 , it's actually beneficial to align the minimum value, i.e., use the same threshold to align the range of two attention maps.
