### ISSUE TITLE
Benchmark Prompts

### ISSUE THREAD

**Issue by tunahansalih** [boschresearch/Divide-and-Bind#4]
Do you have the list of prompts and configurations you have used for benchmarking?

**Comment by YumengLi007** [comment]
Hi @tunahansalih ,
here are the prompts as categorized in Table 1: [prompts.zip](https://github.com/boschresearch/Divide-and-Bind/files/13047272/prompts.zip)

**Comment by tunahansalih** [comment]
Thank you @YumengLi007
