### ISSUE TITLE
Question about model and register_attention_control function

### ISSUE THREAD

**Issue by Wonder1905** [boschresearch/Divide-and-Bind#5]
Hi, thanks for sharing the code , I have a small questions
The model you direct to is :"runwayml/stable-diffusion-v1-5" , but it seems that "register_attention_control" function is not able to regex correctly the cross attention layer in order to register them for storing, which collapse the entire code.

For example in the model mentioned above the layers are not named:"CrossAttention" but "CrossAttn" 

Am I missing something?

**Comment by YumengLi007** [comment]
HI @Wonder1905 , it might be due to different version of the Diffusers library. Code in this repo was based on 0.15.0 version, and it's likely not compatible with the latest Diffusers version.

**Comment by YumengLi007** [comment]
Hi @Wonder1905 , you may try the updated [Divide & Bind pipeline](divide_and_bind/pipeline_divide_and_bind_latest.py), which is now compatible with the latest [Diffusers](https://github.com/huggingface/diffusers) 0.21.4 version.
