### ISSUE TITLE
requires_grad in AttnProcessor

### ISSUE THREAD

**Issue by dain5832** [boschresearch/Divide-and-Bind#8]
Hi, thanks for the wonderful work!
While looking into the code, I found that DivideBindAttnProcessor stores the attention map only if requires_grad is True.
And it differs from the implementation of "attend and excite" which stores every attention map.
Could you explain the purpose of this?

Thanks!

if attention_probs.requires_grad:
            self.attnstore(attention_probs, is_cross, self.place_in_unet)

**Comment by YumengLi007** [comment]
Hi, thanks for your interest! This is similar to the implementation of Attend and Excite [here](https://github.com/huggingface/diffusers/blob/b69fd990ad8026f21893499ab396d969b62bb8cc/src/diffusers/pipelines/stable_diffusion_attend_and_excite/pipeline_stable_diffusion_attend_and_excite.py#L159). It just provides an option to disable saving attention layers for normal inference process without attention optimization on the fly.

**Comment by dain5832** [comment]
Thanks for replying!
But what would be the purpose of not saving the normal inference process?
Does it affect the result?
Also, if I want to visualize the attention map of the generated image, should I remove it?

**Comment by YumengLi007** [comment]
"normal inference process" refers to standard Stable Diffusion process actually, then no attention map is needed for optimization. 
If you want to visualize the attention map, you would need to store the attention here :)
